dubbo:
  application:
    name: stu-service
  registry:
    address: zookeeper://192.168.1.105:2181
  protocol:
    port: -1
  consumer:
    check: false
spring:
  datasource:
    url: jdbc:mysql:///db_stu?serverTimezone=GMT%2B8
    username: root
    password: "000000"
    driver-class-name: com.mysql.cj.jdbc.Driver
